app/assets/javascripts/teachers.coffee
app/assets/stylesheets/teachers.scss
app/controllers/teachers_controller.rb
app/helpers/teachers_helper.rb
app/views/teachers/edit.html.erb
app/views/teachers/new.html.erb
app/views/teachers/show.html.erb
config/routes.rb
test/controllers/teachers_controller_test.rb

teacherモデルの詳細ページを作成

---

app/assets/stylesheets/index.scss
app/assets/stylesheets/teacher_profile.scss
app/models/teacher.rb
app/views/news/index.html.erb
app/views/teachers/show.html.erb

teacher-profileページの機能実装しました

---

app/controllers/news_controller.rb

ニュース記事一覧を投稿された日時の降順で並べ替え

---

app/assets/stylesheets/teacher_profile.scss
app/views/teachers/show.html.erb

先生プロフィール画面デザインしました

---

app/assets/stylesheets/teacher-edit.scss
app/assets/stylesheets/teacher_profile.scss
app/controllers/teachers_controller.rb
app/views/teachers/edit.html.erb
app/views/teachers/show.html.erb
config/routes.rb

Add news create feature

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/students_controller.rb
app/models/student.rb
app/models/teacher.rb
app/models/test.rb
app/views/news/index.html.erb
app/views/news/test.html.erb
app/views/students/show_test.html.erb
config/routes.rb
db/migrate/20200604103510_create_tests.rb
db/schema.rb
db/seeds.rb
test/fixtures/tests.yml
test/models/test_test.rb

スコアのグラフ表示とカレンダー機能に必要なgemのインストールと、各種初期設定。

スコアのグラフ表示とカレンダー機能に必要なgemのインストールと、各種初期設定。

---

app/assets/stylesheets/student_profile.scss
app/controllers/students_controller.rb
app/views/students/show.html.erb
app/views/students/show_test.html.erb
db/migrate/20200604112611_add_column_date_to_tests.rb
db/schema.rb
db/seeds.rb

テストデータベース修正しました

---

app/assets/javascripts/calender.js
app/assets/stylesheets/calender.scss
app/controllers/events_controller.rb
app/views/students/show_calender.html.erb
db/migrate/20200609100837_add_column_to_event.rb
db/migrate/20200609101431_add_column_too_event.rb
db/schema.rb
db/seeds.rb

FullCalenderに対応するため、eventsテーブルのカラムを変更

FullCalenderに対応するため、eventsテーブルのカラムを変更

---

app/assets/stylesheets/calender.scss
app/controllers/events_controller.rb
app/views/events/index.json.jbuilder
app/views/events/show.html.erb

eventのカレンダー表示を実装。

---

app/assets/stylesheets/calender.scss
app/views/events/show.html.erb
db/seeds.rb

eventの詳細表示のデザイン

---

app/assets/stylesheets/calender.scss
app/controllers/events_controller.rb
app/views/events/new.html.erb

eventの新規作成を実装。正常にカレンダー表示されることも確認済み

eventの新規作成を実装。正常にカレンダー表示されることも確認済み

---

app/controllers/events_controller.rb
app/controllers/students_controller.rb
app/views/events/show.html.erb

カレンダーの削除機能を実装。カレンダー表示からも消えることを確認済み。

カレンダーの削除機能を実装。カレンダー表示からも消えることを確認済み。

---

app/assets/stylesheets/show_test.scss
app/controllers/students_controller.rb
app/views/students/show_test.html.erb
db/seeds.rb

グラフデザイン整えました

---

app/assets/stylesheets/show_test.scss
app/assets/stylesheets/title.scss

タイトルデザインを少し編集しました

---

app/assets/javascripts/application.js
app/controllers/teachers_controller.rb
app/views/teachers/show_calender.html.erb
config/routes.rb

teacherにもカレンダー表示と、eventの一覧表示を追加

teacherにもカレンダー表示と、eventの一覧表示を追加

---

app/views/share/_header.html.erb

headerの各メニューにリンクを貼った。

---

app/assets/stylesheets/teacher_show_test.scss

デザイン少し修正しました

---

app/assets/javascripts/application.js
app/assets/stylesheets/calender.scss
app/controllers/events_controller.rb
app/controllers/teachers_controller.rb
app/views/layouts/application.html.erb
app/views/share/_header.html.erb
app/views/students/show_calender.html.erb
app/views/teachers/show_calender.html.erb
config/routes.rb
db/seeds.rb

担当生徒のイベントごとにカレンダー表示。

---

app/assets/stylesheets/index.scss
app/views/news/index.html.erb
app/views/share/_header.html.erb
app/views/teachers/show.html.erb

teacherがアクセスするページにおいて、不足していたリンクを各所に貼った。

teacherがアクセスするページにおいて、不足していたリンクを各所に貼った。

---

app/assets/stylesheets/students.scss
app/controllers/students_controller.rb
app/views/students/index.html.erb
app/views/students/show.html.erb
app/views/teachers/show.html.erb

生徒一覧ページを作成。

---

app/assets/stylesheets/new_learnig_history.scss
app/assets/stylesheets/new_msg.scss
app/assets/stylesheets/show_test.scss
app/assets/stylesheets/student-and-teacher.scss
app/assets/stylesheets/student_profile.scss
app/assets/stylesheets/title.scss
app/views/news/new_msg.html.erb
app/views/share/_student-and-teacher.html.erb
app/views/students/history.html.erb
app/views/students/show_test.html.erb

先生のカレンダーページのデザインしました

---

app/assets/javascripts/application.js
app/assets/javascripts/show_test.js
app/assets/stylesheets/calender.scss
app/controllers/teachers_controller.rb
app/views/teachers/sample.html.erb
app/views/teachers/sample.js.erb
app/views/teachers/show_test.erb
config/routes.rb

テスト新規追加フォームをform_forメソッドに修正。

---

app/assets/javascripts/show_test.js
app/controllers/teachers_controller.rb
app/views/teachers/show_test.erb
config/routes.rb

テスト追加機能を実装。

---

app/assets/javascripts/application.js
app/assets/stylesheets/students.scss
app/views/students/index.html.erb
app/views/teachers/history.html.erb

java scriptで生徒追加機能実装

---

app/assets/javascripts/application.js

javascript検索機能バグ修正しました

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/multiple.js
app/assets/javascripts/webworker.js
app/assets/javascripts/worker.js
app/controllers/home_controller.rb
app/controllers/news_controller.rb
app/controllers/students_controller.rb
app/views/home/student_sign_up.html.erb
app/views/home/top.html.erb
app/views/news/new_learning_history.html.erb
app/views/news/new_msg.html.erb
app/views/students/history.html.erb
app/views/students/show.html.erb
app/views/teachers/history.html.erb
config/initializers/assets.rb
config/routes.rb

Test page design

---

app/assets/stylesheets/students.scss
app/controllers/home_controller.rb
app/controllers/news_controller.rb
app/controllers/students_controller.rb
app/controllers/teachers_controller.rb
app/models/student.rb
app/uploaders/image_uploader.rb
app/views/home/student_sign_up.html.erb
app/views/home/teacher_sign_up.html.erb
app/views/share/_header.html.erb
app/views/students/edit.html.erb
app/views/students/index.html.erb
app/views/students/show.html.erb
app/views/teachers/edit.html.erb
app/views/teachers/history.html.erb
app/views/teachers/show.html.erb
app/views/teachers/show_calender.html.erb
app/views/teachers/show_test.erb
config/routes.rb

生徒、先生の新規作成機能作成完了

---

app/views/news/new_learning_history.html.erb

ストップウォッチのエラー修正しました

---

config/initializers/session_store.rb

ログイン有効期間をsession_store.rbにて修正

---

app/controllers/news_controller.rb
app/views/news/edit_lh.html.erb
app/views/news/index.html.erb
config/routes.rb

leaning_historyの編集フォーム作成

---

app/controllers/news_controller.rb
app/views/news/edit_lh.html.erb
config/routes.rb

学習記録の編集機能を実装

---

app/controllers/students_controller.rb
app/models/student.rb
app/views/students/history.html.erb
app/views/teachers/history.html.erb
db/seeds.rb

学習合計時間を生徒ごとに切り分ける

---

app/controllers/students_controller.rb
app/controllers/teachers_controller.rb
app/views/students/edit.html.erb
app/views/teachers/history.html.erb
db/migrate/20200903132131_add_subject_to_students.rb
db/schema.rb

Studentsテーブルにsubjectカラム追加

---

app/controllers/teachers_controller.rb
app/views/news/index.html.erb
app/views/share/_student-history.erb
app/views/teachers/each_student.html.erb
app/views/teachers/show.html.erb
config/routes.rb

先生が生徒の詳細ページを閲覧できるようにしました

---

app/assets/javascripts/questions.coffee
app/assets/stylesheets/questions.scss
app/controllers/questions_controller.rb
app/helpers/questions_helper.rb
test/controllers/questions_controller_test.rb

Questionsコントローラー作成

---

app/views/news/index.html.erb
app/views/replies/teacher_reply.html.erb

questionsフォーム修正しました

---

app/controllers/news_controller.rb
app/views/news/index.html.erb

news_fieldページにquestionデータ表示成功

---

app/controllers/news_controller.rb
app/controllers/replies_controller.rb
app/uploaders/image_uploader.rb
app/views/news/index.html.erb
app/views/replies/new.html.erb
db/migrate/20200908131956_add_which_to_replies.rb
db/schema.rb

question機能完成しました。また、whichカラムをrepliesテーブルに追加しました

question機能完成しました。また、whichカラムをrepliesテーブルに追加しました

---

app/models/question.rb
app/views/news/index.html.erb

外部キーのdeleteエラー直しました

---

app/views/replies/new.html.erb

プレビュー画像の大きさを制限

---

app/controllers/students_controller.rb
app/views/replies/new.html.erb
app/views/students/edit.html.erb
db/migrate/20200911133418_add_mail_to_students.rb
db/schema.rb

メール登録フォーム作成しました。またStudentテーブルにmailカラム追加しました。

メール登録フォーム作成しました。またStudentテーブルにmailカラム追加しました。

---

config/environments/development.rb

メール送信用のアカウントの設定を変更。

---

app/controllers/replies_controller.rb
app/mailers/notification_mailer.rb
app/views/notification_mailer/send_reply.html.erb

リプライ投稿時にメールを送信

---

app/controllers/news_controller.rb

newsの並び替えを修正

---

app/controllers/replies_controller.rb
app/models/reply.rb
app/uploaders/image_uploader.rb
app/views/news/index.html.erb
app/views/replies/new.html.erb
db/migrate/20201004092345_add_image_to_replies.rb
db/schema.rb

リプライに画像添付機能追加

---

app/views/home/test.html.erb
db/schema.rb

restartTest()からreset()を消しました。エラーがでるので

restartTest()からreset()を消しました。エラーがでるので

---

app/controllers/home_controller.rb
app/models/wordbook.rb
app/views/home/level.html.erb
app/views/home/show.html.erb
app/views/home/test.html.erb
config/routes.rb

単語帳とレベルの紐付けおよび表示を実装

---

app/views/home/test.html.erb

問題終了後の成績表示

---

app/controllers/home_controller.rb
app/models/wordbook.rb
app/views/home/test.html.erb

Add wordtest func

---

app/views/home/test.html.erb

成績結果の表のデザイン変更

---

app/models/wordbook.rb
app/views/home/test.html.erb

選択肢のシャッフルを実装

---

app/views/home/test.html.erb

問題表示可能にしました

---

app/assets/javascripts/results.coffee
app/assets/stylesheets/results.scss
app/controllers/home_controller.rb
app/controllers/results_controller.rb
app/helpers/results_helper.rb
app/models/result.rb
app/models/word_test.rb
app/models/wordbook.rb
app/views/home/test.html.erb
app/views/results/create.html.erb
config/routes.rb
db/migrate/20201008105353_create_word_tests.rb
db/migrate/20201008105543_add_references_word_test.rb
db/migrate/20201008111705_remove_referenece_words.rb
db/migrate/20201008112448_add_referenecs_column_result.rb
db/schema.rb
test/controllers/results_controller_test.rb
test/fixtures/word_tests.yml
test/models/word_test_test.rb

テストの結果を保存させるためのテーブルを作成

---

app/controllers/results_controller.rb
app/views/home/test.html.erb

ワードテスト結果を保存

---

app/views/home/test.html.erb

PostResultエラー

---

app/views/home/test.html.erb

分からないボタンを押下した際も同様の挙動にする

---

app/models/word.rb
app/models/wordbook.rb
app/views/home/level.html.erb
app/views/home/test.html.erb

正解の選択肢が重複してしまうバグを修正。間違えた回数を計算して表示。

正解の選択肢が重複してしまうバグを修正。間違えた回数を計算して表示。

---

app/controllers/home_controller.rb
app/models/word.rb
app/models/wordbook.rb
app/views/home/level.html.erb
app/views/home/test.html.erb
config/routes.rb

間違った単語をテストする機能を追加

---

app/controllers/news_controller.rb
app/views/news/index.html.erb

collapseエラー修正しました

---

app/models/result.rb
app/views/home/test.html.erb
app/views/news/index.html.erb

正解の数を表示できるようにする

---

app/controllers/word_tests_controller.rb
app/models/student.rb
app/views/word_tests/index.html.erb
app/views/word_tests/show.html.erb

生徒がワードテストの結果詳細を確認できるようにする

---

app/views/news/index.html.erb
app/views/share/_header.html.erb

news_fieldの単語テスト結果デザイン

---

Gemfile
Gemfile.lock
app/views/teachers/fujita.html.erb
lib/tasks/scrape.rake

スクレイプするための準備

---

app/assets/stylesheets/results.css
app/assets/stylesheets/results.css.map
app/assets/stylesheets/word_tests.css
app/assets/stylesheets/word_tests.css.map
app/models/word.rb
lib/tasks/scrape.rake

1900単語をスクレイピングで取得

---

app/controllers/home_controller.rb
app/models/word.rb
app/models/wordbook.rb
app/views/home/choise_retest.html.erb
app/views/home/level.html.erb
app/views/home/test.html.erb
config/routes.rb
lib/tasks/scrape.rake

システム英単語のスクレイピングを実装

---

app/models/student.rb
app/views/home/level.html.erb
app/views/home/show.html.erb

ワードテストの進捗用のプログレスバーを実装

---

app/models/student.rb
app/views/home/level.html.erb
app/views/home/show.html.erb

プログレスバーをパーセント表記に修正

---

app/views/words/index.html.erb
lib/tasks/scrape.rake

管理者ページの単語検索機能追加

---

lib/tasks/scrape.rake

古文単語スクレイピングコード

---

app/controllers/home_controller.rb
app/controllers/news_controller.rb
app/models/old_result.rb
app/models/old_word_test.rb
db/migrate/20201015114611_create_old_word_tests.rb
db/migrate/20201015114734_create_old_results.rb
db/schema.rb
test/fixtures/old_results.yml
test/fixtures/old_word_tests.yml
test/models/old_result_test.rb
test/models/old_word_test_test.rb

OldResult,OldWordTestモデル作成しました

OldResult,OldWordTestモデル作成しました

---

db/migrate/20201015121813_change_column_name_old_result.rb
db/migrate/20201015122328_add_column_name_old_result.rb
db/schema.rb

マイグレーションの修正

---

app/controllers/home_controller.rb
app/models/old_word.rb
app/models/old_wordbook.rb
config/routes.rb

テストに渡す古典単語を用意

---

app/models/old_word.rb
app/models/old_wordbook.rb

間違えた単語数を計算するメソッドを実装

---

app/assets/javascripts/old_results.coffee
app/assets/stylesheets/old_results.scss
app/controllers/home_controller.rb
app/controllers/old_results_controller.rb
app/helpers/old_results_helper.rb
app/models/old_result.rb
app/views/home/japanesetest.html.erb
app/views/home/jwords.html.erb
config/routes.rb
test/controllers/old_results_controller_test.rb

Old word func

---

app/models/old_wordbook.rb
app/views/home/japanesetest.html.erb

古文テスト内で漢字表記を表示

---

app/views/news/index.html.erb
lib/tasks/scrape.rake

ターゲット英熟語1000テスト追加

---

lib/tasks/scrape.rake

user-agent変更

---

app/controllers/home_controller.rb

古典単語のテスト数を修正

---

app/models/old_wordbook.rb

古典単語のテスト抽出を修正

---

app/models/student.rb
app/views/home/show.html.erb

古典単語テストの進捗プログレスを実装

---

Gemfile
Gemfile.lock
app/assets/stylesheets/index.scss
app/uploaders/image_uploader.rb
app/views/news/index.html.erb
app/views/share/_header.html.erb
app/views/share/_student-history.erb
config/initializers/carrierwave.rb
environments/db.env
lib/tasks/deleteimage.rake
lib/tasks/scrape.rake

画像データをAWS,S3に移行

---

config/database.yml

本番環境のデータベース設定を追加

---

Gemfile
Gemfile.lock

本番環境用にdotenv-railsを追加

---

lib/tasks/db_csv.rake

古典単語関連のテーブルもCSVエクスポートするよう修正

---

lib/tasks/db_csv.rake

CSVインポート用のコマンドを作成

---

lib/tasks/db_csv.rake

CSVインポート時の不具合を修正

---

lib/tasks/db_csv.rake

CSVインポート時にIDを指定するようにする

---

app/controllers/news_controller.rb

newsコントローラを作成

---

app/controllers/news_controller.rb
app/views/news/index.html.erb

newsコントローラとindexのビューを修正

---

app/views/news/index.html.erb

ニュースフィールドのエラー修正

---

app/controllers/news_controller.rb
app/views/news/index.html.erb

news_fieldで単語テスト結果が表示されない不具合を修正

news_fieldで単語テスト結果が表示されない不具合を修正

---

app/views/news/index.html.erb

newsfield修正

---

app/assets/stylesheets/index.scss

indexpage修正

---

app/controllers/news_controller.rb

news_fieldにて、一週間のみデータを表示するよう修正

news_fieldにて、一週間のみデータを表示するよう修正

---

.gitignore
app/controllers/students_controller.rb
app/views/students/edit.html.erb
app/views/students/edit_password.html.erb
config/routes.rb

パスワード編集機能を実装

---

app/controllers/news_controller.rb

ニュースフィールドに表示するデータを直近5日に変更

---

app/models/aggregate.rb
app/models/student.rb
app/models/wordbook.rb
app/views/home/level.html.erb
app/views/home/show.html.erb
db/migrate/20201115125506_create_aggregates.rb
db/schema.rb
lib/tasks/aggregates.rake
test/fixtures/aggregates.yml
test/models/aggregate_test.rb

単語テスト選択画面の表示速度を高速化

---

app/assets/javascripts/aggregates.coffee
app/assets/stylesheets/aggregates.scss
app/controllers/aggregates_controller.rb
app/controllers/home_controller.rb
app/helpers/aggregates_helper.rb
app/views/aggregates/index.html.erb
app/views/home/test.html.erb
config/routes.rb
test/controllers/aggregates_controller_test.rb

単語テスト成績計算ロジックを編集
